//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHDDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctthongbao
    {
        public System.Guid ctthongbao_id { get; set; }
        public string orgid { get; set; }
        public string mau_so { get; set; }
        public string ky_hieu { get; set; }
        public Nullable<int> so_luong { get; set; }
        public string tu_so { get; set; }
        public string den_so { get; set; }
        public Nullable<System.DateTime> ngay_bd_sd { get; set; }
        public string hetso { get; set; }
        public string value { get; set; }
        public int id { get; set; }
        public Nullable<bool> tt78 { get; set; }
    }
}
