//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHDDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export_Invoice
    {
        public int id { get; set; }
        public string orgid { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public string so_don_hang { get; set; }
        public string mau_so { get; set; }
        public string ky_hieu { get; set; }
        public string inv_invoicenumber { get; set; }
        public string inv_InvoiceAuth_id { get; set; }
        public string inv_invoicecode_id { get; set; }
        public string json_data { get; set; }
        public string trang_thai_xuat { get; set; }
    }
}
