//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHDDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_install
    {
        public string code { get; set; }
        public string id_token { get; set; }
        public string access_token { get; set; }
        public string sid { get; set; }
        public string orgid { get; set; }
    }
}
