//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHDDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Order
    {
        public string id_order { get; set; }
        public string orgid { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public string inv_invoicecode_id { get; set; }
        public string inv_invoiceseries { get; set; }
        public string mau_so { get; set; }
        public Nullable<bool> tt78 { get; set; }
    }
}
