//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHDDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_info
    {
        public string orgid { get; set; }
        public string orgname { get; set; }
        public string orgcat { get; set; }
        public string sid { get; set; }
        public string name { get; set; }
        public string middle_name { get; set; }
        public string email { get; set; }
        public string nbf { get; set; }
        public string exp { get; set; }
        public string iss { get; set; }
        public string aud { get; set; }
        public string iat { get; set; }
        public string c_hash { get; set; }
        public string sub { get; set; }
        public string locale { get; set; }
        public string auth_time { get; set; }
        public string idp { get; set; }
        public string id_token { get; set; }
        public string mst { get; set; }
        public string link { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string myharavan_domain { get; set; }
        public string customer_email { get; set; }
        public string phone { get; set; }
    }
}
